<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BTS;

class BTSSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run() : void
    {
        // Data contoh untuk tabel bts
        $btsData = [
            [
                'nama' => 'BTS Merdeka',
                'alamat' => 'Jl. Mawar No. 1, Jakarta',
                'id_jenis_bts' => 1,
                'latitude' => -6.200000,
                'longitude' => 106.816666,
                'tinggi_tower' => 50,
                'panjang_tanah' => 100,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 1,
                'id_pemilik' => 1,
                'id_wilayah' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'BTS Sejahtera',
                'alamat' => 'Jl. Melati No. 2, Jakarta',
                'id_jenis_bts' => 2,
                'latitude' => -6.2465751,
                'longitude' => 106.826666,
                'tinggi_tower' => 45,
                'panjang_tanah' => 90,
                'lebar_tanah' => 45,
                'ada_genset' => false,
                'ada_tembok_batas' => true,
                'id_user_pic' => 2,
                'id_pemilik' => 2,
                'id_wilayah' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'nama' => 'BTS Mawar',
                'alamat' => 'Jl. Kenanga No. 3, Bandung',
                'id_jenis_bts' => 3,
                'latitude' => -6.914744,
                'longitude' => 107.609810,
                'tinggi_tower' => 60,
                'panjang_tanah' => 110,
                'lebar_tanah' => 55,
                'ada_genset' => true,
                'ada_tembok_batas' => false,
                'id_user_pic' => 3,
                'id_pemilik' => 3,
                'id_wilayah' => 3,
                'created_by' => 3,
                'edited_by' => 3,
            ],
            [
                'nama' => 'BTS Nusantara',
                'alamat' => 'Jl. Anggrek No. 4, Surabaya',
                'id_jenis_bts' => 4,
                'latitude' => -7.257472,
                'longitude' => 112.752090,
                'tinggi_tower' => 55,
                'panjang_tanah' => 120,
                'lebar_tanah' => 60,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 4,
                'id_pemilik' => 4,
                'id_wilayah' => 4,
                'created_by' => 4,
                'edited_by' => 4,
            ],
            [
                'nama' => 'BTS Jaya',
                'alamat' => 'Jl. Flamboyan No. 5, Medan',
                'id_jenis_bts' => 5,
                'latitude' => 3.595196,
                'longitude' => 98.672226,
                'tinggi_tower' => 65,
                'panjang_tanah' => 130,
                'lebar_tanah' => 65,
                'ada_genset' => false,
                'ada_tembok_batas' => true,
                'id_user_pic' => 5,
                'id_pemilik' => 5,
                'id_wilayah' => 5,
                'created_by' => 5,
                'edited_by' => 5,
            ],
            [
                'nama' => 'BTS Cahaya',
                'alamat' => 'Jl. Dahlia No. 6, Makassar',
                'id_jenis_bts' => 6,
                'latitude' => -5.147665,
                'longitude' => 119.432732,
                'tinggi_tower' => 70,
                'panjang_tanah' => 140,
                'lebar_tanah' => 70,
                'ada_genset' => true,
                'ada_tembok_batas' => false,
                'id_user_pic' => 6,
                'id_pemilik' => 6,
                'id_wilayah' => 6,
                'created_by' => 6,
                'edited_by' => 6,
            ],
            [
                'nama' => 'BTS Gemilang',
                'alamat' => 'Jl. Kamboja No. 7, Semarang',
                'id_jenis_bts' => 7,
                'latitude' => -6.966667,
                'longitude' => 110.416664,
                'tinggi_tower' => 75,
                'panjang_tanah' => 150,
                'lebar_tanah' => 75,
                'ada_genset' => false,
                'ada_tembok_batas' => true,
                'id_user_pic' => 7,
                'id_pemilik' => 7,
                'id_wilayah' => 7,
                'created_by' => 7,
                'edited_by' => 7,
            ],
            [
                'nama' => 'BTS Harapan',
                'alamat' => 'Jl. Teratai No. 8, Palembang',
                'id_jenis_bts' => 8,
                'latitude' => -2.976074,
                'longitude' => 104.775431,
                'tinggi_tower' => 80,
                'panjang_tanah' => 160,
                'lebar_tanah' => 80,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 8,
                'id_pemilik' => 8,
                'id_wilayah' => 8,
                'created_by' => 8,
                'edited_by' => 8,
            ],
            [
                'nama' => 'BTS Makmur',
                'alamat' => 'Jl. Mawar No. 9, Bali',
                'id_jenis_bts' => 9,
                'latitude' => -8.409518,
                'longitude' => 115.188919,
                'tinggi_tower' => 85,
                'panjang_tanah' => 170,
                'lebar_tanah' => 85,
                'ada_genset' => false,
                'ada_tembok_batas' => false,
                'id_user_pic' => 9,
                'id_pemilik' => 9,
                'id_wilayah' => 9,
                'created_by' => 9,
                'edited_by' => 9,
            ],
            [
                'nama' => 'BTS Intan',
                'alamat' => 'Jl. Cempaka No. 10, Balikpapan',
                'id_jenis_bts' => 10,
                'latitude' => -1.265386,
                'longitude' => 116.831223,
                'tinggi_tower' => 90,
                'panjang_tanah' => 180,
                'lebar_tanah' => 90,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 10,
                'id_pemilik' => 10,
                'id_wilayah' => 10,
                'created_by' => 10,
                'edited_by' => 10,
            ],




            [
                'nama' => 'BTS Pahlawan',
                'alamat' => 'Jl. Melati No. 15, Jayapura',
                'id_jenis_bts' => 2,
                'latitude' => -2.533710,
                'longitude' => 140.718132,
                'tinggi_tower' => 65,
                'panjang_tanah' => 60,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => false,
                'id_user_pic' => 11,
                'id_pemilik' => 11,
                'id_wilayah' => 2,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Tangguh',
                'alamat' => 'Jl. Dahlia No. 16, Kupang',
                'id_jenis_bts' => 1,
                'latitude' => -10.177225,
                'longitude' => 123.607032,
                'tinggi_tower' => 75,
                'panjang_tanah' => 50,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 12,
                'id_pemilik' => 9,
                'id_wilayah' => 2,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Cahaya',
                'alamat' => 'Jl. Kamboja No. 11, Banjarmasin',
                'id_jenis_bts' => 6,
                'latitude' => -3.316694,
                'longitude' => 114.590756,
                'tinggi_tower' => 40,
                'panjang_tanah' => 60,
                'lebar_tanah' => 45,
                'ada_genset' => false,
                'ada_tembok_batas' => true,
                'id_user_pic' => 13,
                'id_pemilik' => 7,
                'id_wilayah' => 16,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Pertiwi',
                'alamat' => 'Jl. Flamboyan No. 8, Denpasar',
                'id_jenis_bts' => 5,
                'latitude' => -8.670458,
                'longitude' => 115.212629,
                'tinggi_tower' => 45,
                'panjang_tanah' => 50,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 14,
                'id_pemilik' => 9,
                'id_wilayah' => 51,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Nusantara',
                'alamat' => 'Jl. Mawar No. 6, Palembang',
                'id_jenis_bts' => 4,
                'latitude' => -2.990934,
                'longitude' => 104.756557,
                'tinggi_tower' => 65,
                'panjang_tanah' => 75,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 15,
                'id_pemilik' => 6,
                'id_wilayah' => 34,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Sejahtera',
                'alamat' => 'Jl. Seruni No. 7, Makassar',
                'id_jenis_bts' => 9,
                'latitude' => -5.147665,
                'longitude' => 119.432731,
                'tinggi_tower' => 75,
                'panjang_tanah' => 70,
                'lebar_tanah' => 65,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 16,
                'id_pemilik' => 7,
                'id_wilayah' => 21,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Sukses',
                'alamat' => 'Jl. Tulip No. 4, Yogyakarta',
                'id_jenis_bts' => 10,
                'latitude' => -7.795580,
                'longitude' => 110.369490,
                'tinggi_tower' => 50,
                'panjang_tanah' => 40,
                'lebar_tanah' => 40,
                'ada_genset' => true,
                'ada_tembok_batas' => false,
                'id_user_pic' => 17,
                'id_pemilik' => 4,
                'id_wilayah' => 38,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Inspirasi',
                'alamat' => 'Jl. Cempaka No. 17, Ambon',
                'id_jenis_bts' => 2,
                'latitude' => -3.656073,
                'longitude' => 128.190758,
                'tinggi_tower' => 60,
                'panjang_tanah' => 60,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 18,
                'id_pemilik' => 12,
                'id_wilayah' => 26,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Lestari',
                'alamat' => 'Jl. Teratai No. 19, Ternate',
                'id_jenis_bts' => 7,
                'latitude' => 0.789275,
                'longitude' => 127.360917,
                'tinggi_tower' => 50,
                'panjang_tanah' => 50,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => false,
                'id_user_pic' => 19,
                'id_pemilik' => 12,
                'id_wilayah' => 27,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Sentosa',
                'alamat' => 'Jl. Melati No. 27, Sorong',
                'id_jenis_bts' => 8,
                'latitude' => -0.878370,
                'longitude' => 131.257090,
                'tinggi_tower' => 75,
                'panjang_tanah' => 65,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 20,
                'id_pemilik' => 11,
                'id_wilayah' => 25,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Wijaya',
                'alamat' => 'Jl. Mawar No. 30, Kupang',
                'id_jenis_bts' => 10,
                'latitude' => -10.177225,
                'longitude' => 123.607032,
                'tinggi_tower' => 50,
                'panjang_tanah' => 60,
                'lebar_tanah' => 50,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 21,
                'id_pemilik' => 1,
                'id_wilayah' => 2,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Persada',
                'alamat' => 'Jl. Melati No. 31, Pontianak',
                'id_jenis_bts' => 1,
                'latitude' => -0.022574,
                'longitude' => 109.333247,
                'tinggi_tower' => 40,
                'panjang_tanah' => 40,
                'lebar_tanah' => 40,
                'ada_genset' => true,
                'ada_tembok_batas' => false,
                'id_user_pic' => 22,
                'id_pemilik' => 8,
                'id_wilayah' => 17,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Pesona',
                'alamat' => 'Jl. Kenanga No. 32, Pekanbaru',
                'id_jenis_bts' => 8,
                'latitude' => 0.533333,
                'longitude' => 101.450000,
                'tinggi_tower' => 65,
                'panjang_tanah' => 100,
                'lebar_tanah' => 60,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 23,
                'id_pemilik' => 6,
                'id_wilayah' => 3,
                'created_by' => 1,
                'edited_by' => 1
            ],
            [
                'nama' => 'BTS Elok',
                'alamat' => 'Jl. Mawar No. 33, Tanjung Selor',
                'id_jenis_bts' => 6,
                'latitude' => 2.840000,
                'longitude' => 117.367500,
                'tinggi_tower' => 50,
                'panjang_tanah' => 40,
                'lebar_tanah' => 40,
                'ada_genset' => true,
                'ada_tembok_batas' => true,
                'id_user_pic' => 24,
                'id_pemilik' => 5,
                'id_wilayah' => 13,
                'created_by' => 1,
                'edited_by' => 1
            ],
            // Tambahkan data lainnya sesuai kebutuhan
        ];

        // Insert data ke dalam database
        foreach ($btsData as $bts) {
            BTS::create($bts);
        }
    }
}
