<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Monitoring;
use Carbon\Carbon;

class MonitoringSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data contoh untuk tabel monitoring
        $monitoringData = [
            [
                'tahun' => 2024,
                'id_bts' => 1,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 30)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 24)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 1,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 20)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 14)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 1,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 10)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 4)->toDateString(),
                'id_kondisi_bts' => '3',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 1,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 30)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 24)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 1,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 4)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 1,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 4)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 1,
                'tgl_generate' => Carbon::createFromDate(2024, 7, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 7, 4)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 2,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 30)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 26)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 2,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 30)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 26)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 2,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 30)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 26)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 2,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 30)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 26)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 2,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 30)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 26)->toDateString(),
                'id_kondisi_bts' => '3',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 2,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 30)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 26)->toDateString(),
                'id_kondisi_bts' => '3',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 3,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 24)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 16)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 3,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 24)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 16)->toDateString(),
                'id_kondisi_bts' => '3',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 3,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 24)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 16)->toDateString(),
                'id_kondisi_bts' => '3',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 3,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 24)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 16)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 3,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 24)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 16)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 3,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 24)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 16)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 3,
                'tgl_generate' => Carbon::createFromDate(2024, 7, 24)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 7, 16)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 4,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 11)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 3)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 4,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 11)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 3)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 4,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 11)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 3)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 4,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 11)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 3)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 4,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 11)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 3)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 4,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 11)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 3)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 5,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 6)->toDateString(),
                'id_kondisi_bts' => '3',
                'id_user_surveyor' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 5,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 6)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 5,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 6)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 5,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 6)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 5,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 6)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 5,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 6)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 5,
                'tgl_generate' => Carbon::createFromDate(2024, 7, 21)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 7, 6)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 6,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 12)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 5)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 3,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 6,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 12)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 5)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 3,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 6,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 12)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 5)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 3,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 6,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 12)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 5)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 3,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 6,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 12)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 5)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 3,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 6,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 12)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 5)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 3,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 7,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 28)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 26)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 7,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 28)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 26)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 7,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 28)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 26)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 7,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 28)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 26)->toDateString(),
                'id_kondisi_bts' => '3',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 7,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 28)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 26)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 7,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 28)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 26)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 7,
                'tgl_generate' => Carbon::createFromDate(2024, 7, 24)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 7, 20)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 8,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 14)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 2)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 8,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 14)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 2)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 8,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 14)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 2)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 8,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 14)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 2)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 8,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 14)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 2)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 8,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 14)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 2)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 8,
                'tgl_generate' => Carbon::createFromDate(2024, 7, 14)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 7, 2)->toDateString(),
                'id_kondisi_bts' => '4',
                'id_user_surveyor' => 2,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 9,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 9)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 1)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 9,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 9)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 1)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 9,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 9)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 1)->toDateString(),
                'id_kondisi_bts' => '2',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 9,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 9)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 1)->toDateString(),
                'id_kondisi_bts' => '3',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 9,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 9)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 1)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 9,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 9)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 1)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 9,
                'tgl_generate' => Carbon::createFromDate(2024, 7, 9)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 7, 1)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 10,
                'tgl_generate' => Carbon::createFromDate(2024, 1, 22)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 1, 13)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 10,
                'tgl_generate' => Carbon::createFromDate(2024, 2, 22)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 2, 13)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 10,
                'tgl_generate' => Carbon::createFromDate(2024, 3, 22)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 3, 13)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 10,
                'tgl_generate' => Carbon::createFromDate(2024, 4, 22)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 4, 13)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 10,
                'tgl_generate' => Carbon::createFromDate(2024, 5, 22)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 5, 13)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
            [
                'tahun' => 2024,
                'id_bts' => 10,
                'tgl_generate' => Carbon::createFromDate(2024, 6, 22)->toDateString(),
                'tgl_kunjungan' => Carbon::createFromDate(2024, 6, 13)->toDateString(),
                'id_kondisi_bts' => '1',
                'id_user_surveyor' => 1,
                'created_by' => 2,
                'edited_by' => 2,
            ],
        ];

        // Insert data ke dalam database
        foreach ($monitoringData as $monitoring) {
            Monitoring::create($monitoring);
        }
    }
}