<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Wilayah;

class WilayahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data wilayah contoh
        $wilayahs = [
            [
                'nama' => 'Indonesia',
                'id_parent' => null,
                'level' => 1,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Nangggoroe Aceh Darussalam',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Riau',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sumatera Utara',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sumatera Barat',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sumatera Selatan',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Banten',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Daerah Khusus Jakarta',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Jawa Barat',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Daerah Istimewa Yogyakarta',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Jawa Tengah',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Jawa Timur',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Kalimantan Utara',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Kalimantan Timur',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Kalimantan Tengah',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Kalimantan Selatan',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Kalimantan Barat',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sulawesi Utara',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sulawesi Tengah',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sulawesi Tenggara',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sulawesi Selatan',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sulawesi Barat',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Bali',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Nusa Tenggara Barat',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Nusa Tenggara Timur',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Maluku',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Maluku Utara',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Papua',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Papua Barat',
                'id_parent' => 1,
                'level' => 2,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Banda Aceh',
                'id_parent' => 2,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Siak',
                'id_parent' => 3,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Medan',
                'id_parent' => 4,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Kepulauan Mentawai',
                'id_parent' => 5,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Palembang',
                'id_parent' => 6,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Serang',
                'id_parent' => 7,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Jakarta Pusat',
                'id_parent' => 8,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Bandung',
                'id_parent' => 9,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Yogyakarta',
                'id_parent' => 10,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Surakarta',
                'id_parent' => 11,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Surabaya',
                'id_parent' => 12,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Malinau',
                'id_parent' => 13,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Balikpapan',
                'id_parent' => 14,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Murung Raya',
                'id_parent' => 15,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Banjarmasin',
                'id_parent' => 16,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Sambas',
                'id_parent' => 17,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Minahasa',
                'id_parent' => 18,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Tolitoli',
                'id_parent' => 19,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Buton',
                'id_parent' => 20,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Gowa',
                'id_parent' => 21,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Mamuju',
                'id_parent' => 22,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Denpasar',
                'id_parent' => 23,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Bima',
                'id_parent' => 24,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Kupang',
                'id_parent' => 25,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Kepulauan Aru',
                'id_parent' => 26,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Halmahera',
                'id_parent' => 27,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Jayapura',
                'id_parent' => 28,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
            [
                'nama' => 'Manokwari',
                'id_parent' => 29,
                'level' => 3,
                'created_by' => 1,
                'edited_by' => 1,
            ],
        ];

        // Insert data wilayah ke dalam database
        foreach ($wilayahs as $wilayah) {
            Wilayah::create($wilayah);
        }
    }
}
